// batmon — charging screen for the Miyoo Mini Plus.
//
// Shown when the device is powered on while plugged in. Draws a battery with a REAL fill level and
// a percentage, refreshed once a second.
//
// Rewritten from the original, which had four problems worth naming because each was reported as
// a fault:
//   1. It displayed a STATIC png (charging-640-480.png) — no level, no progress, no feedback.
//   2. It blanked the panel after 3s and then blocked forever, so booting on the charger looked
//      exactly like a hung device.
//   3. Unplugging the charger ran `shutdown` — pulling the cable POWERED THE DEVICE OFF.
//   4. Its wait loop had no sleep, pinning a Cortex-A7 core at 100% for the whole charging
//      session: slower charging, more heat, on a fork whose entire thesis is the opposite.
//
// It also dropped the SDL 1.2 + SDL_image dependency (which this fork does not ship — it resolved
// only against the stock rootfs). Everything here is libc + the framebuffer + i2c.
//
// Behaviour now:
//   POWER pressed  -> exit 0, boot continues normally
//   charger pulled -> exit 0, boot continues normally  (NEVER powers off)
//   idle           -> dims the backlight, any key restores it; never blocks input
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>
#include <poll.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/time.h>
#include <linux/fb.h>
#include <linux/i2c.h>
#include <linux/i2c-dev.h>

#define AXPDEV "/dev/i2c-1"
#define AXPID  0x34

// Minimal evdev ABI (see platform.c: <linux/input.h> BTN_* collide with MinUI's own names)
struct bm_event { struct timeval time; unsigned short type; unsigned short code; int value; };
#define BM_EV_KEY   0x01
#define KEY_POWER_  116

#define DUTY_PATH "/sys/class/pwm/pwmchip0/pwm0/duty_cycle"

static int axp_read(unsigned char address) {
	struct i2c_msg msg[2];
	struct i2c_rdwr_ioctl_data packets;
	unsigned char val = 0;
	int fd = open(AXPDEV, O_RDWR);
	if (fd < 0) return -1;
	ioctl(fd, I2C_TIMEOUT, 5);
	ioctl(fd, I2C_RETRIES, 1);
	msg[0].addr = AXPID; msg[0].flags = 0;        msg[0].len = 1; msg[0].buf = &address;
	msg[1].addr = AXPID; msg[1].flags = I2C_M_RD; msg[1].len = 1; msg[1].buf = &val;
	packets.nmsgs = 2; packets.msgs = &msg[0];
	int ret = ioctl(fd, I2C_RDWR, &packets);
	close(fd);
	return ret < 0 ? -1 : val;
}

// reg 0x00: bit7 = ACIN present, bit4 = VBUS usable, bit2 = battery current direction.
// Returns 1 externally powered, 0 running on battery, -1 READ FAILED.
// The -1 matters: minui and keymon poll the same AXP over the same i2c bus, so a contended
// read fails transiently and must NOT be read as "unplugged".
// We gate on POWER PRESENT rather than bit2, because bit2 clears once the battery is full
// (no current flows into a charged cell) even though the cable is still attached.
static int isPowered(void) {
	int v = axp_read(0x00);
	if (v < 0) return -1;
	return (v & 0x80) || (v & 0x10) ? 1 : 0;   // ACIN present or VBUS usable
}
// Actively pushing current into the battery (vs. plugged in and already full).
static int isCharging(void) { int v = axp_read(0x00); return v < 0 ? -1 : ((v & 0x04) != 0); }
// reg 0xB9 bits[6:0] = fuel gauge percentage. VERIFIED: matches /customer/app/axp_test exactly.
static int battPercent(void) {
	int v = axp_read(0xB9);
	if (v < 0) return -1;
	v &= 0x7F;
	return v > 100 ? -1 : v;   // the gauge is known to return garbage occasionally — reject it
}

// ---- framebuffer ----
static int fb_fd = -1;
static uint32_t* fb = NULL;
static int FBW = 640, FBH = 480, FBP = 640; // pixels per row

// The panel is mounted INVERTED. Anything written straight into the framebuffer bypasses the
// MI_GFX rotate the rest of the stack uses, so plot 180-rotated here or it renders upside down.
static inline void px(int x, int y, uint32_t c) {
	if (x < 0 || y < 0 || x >= FBW || y >= FBH) return;
	fb[(FBH - 1 - y) * FBP + (FBW - 1 - x)] = c;
}
static void fillRect(int x, int y, int w, int h, uint32_t c) {
	for (int j = 0; j < h; j++) for (int i = 0; i < w; i++) px(x+i, y+j, c);
}
static void frameRect(int x, int y, int w, int h, int t, uint32_t c) {
	fillRect(x, y, w, t, c); fillRect(x, y+h-t, w, t, c);
	fillRect(x, y, t, h, c); fillRect(x+w-t, y, t, h, c);
}

// Digits 0-9 and '%' pre-rasterised from BPreplayBold-unhinted.otf — the SAME face the launcher
// uses, and the one the reference charging screen is set in. Generated by
// tools/gen-batmon-font.py and embedded, so we get the exact typeface without linking SDL_ttf or
// any image library into a binary that runs before the menu exists.
// (The previous 5x7 grid could not imitate a rounded bold face; thickening it just made the wrong
// font heavier, which is exactly how it read on device.)
#include "font.h"

static int textWidth(const char* t) {
	int w = 0;
	for (const char* p = t; *p; p++) {
		int gi = (*p >= '0' && *p <= '9') ? *p - '0' : (*p == '%' ? 10 : -1);
		if (gi >= 0) w += BM_ADV[gi];
	}
	return w;
}
static void drawText(const char* t, int x, int y, uint32_t c) {
	for (const char* p = t; *p; p++) {
		int gi = (*p >= '0' && *p <= '9') ? *p - '0' : (*p == '%' ? 10 : -1);
		if (gi < 0) continue;
		for (int r = 0; r < BM_GH; r++) {
			unsigned int bits = BM_FONT[gi][r];
			for (int b = 0; b < BM_GW; b++)
				if (bits & (1u << b)) px(x + b, y + r, c);
		}
		x += BM_ADV[gi];
	}
}

static void setDuty(int v) {
	int fd = open(DUTY_PATH, O_WRONLY);
	if (fd < 0) return;
	char b[8]; int n = snprintf(b, sizeof b, "%d", v);
	if (write(fd, b, n) < 0) { /* best effort */ }
	close(fd);
}
static int getDuty(void) {
	int fd = open(DUTY_PATH, O_RDONLY);
	if (fd < 0) return -1;
	char b[16] = {0};
	int n = read(fd, b, sizeof b - 1);
	close(fd);
	return n > 0 ? atoi(b) : -1;
}

// Rounded-rect membership. The reference art is rounded on the outline, the fill and the nub;
// square corners read as a different (cheaper-looking) design at a glance.
static inline int inRound(int x, int y, int rx, int ry, int w, int h, int r) {
	if (x < rx || y < ry || x >= rx + w || y >= ry + h) return 0;
	if (r <= 0) return 1;
	int dx = 0, dy = 0;
	if (x < rx + r)                 dx = rx + r - x;
	else if (x > rx + w - 1 - r)    dx = x - (rx + w - 1 - r);
	if (y < ry + r)                 dy = ry + r - y;
	else if (y > ry + h - 1 - r)    dy = y - (ry + h - 1 - r);
	if (dx == 0 || dy == 0) return 1;
	return dx*dx + dy*dy <= r*r;
}
static void fillRound(int x, int y, int w, int h, int r, uint32_t c) {
	for (int j = 0; j < h; j++)
		for (int i = 0; i < w; i++)
			if (inRound(x+i, y+j, x, y, w, h, r)) px(x+i, y+j, c);
}

// Geometry is DERIVED from docs/img/charging-screen.png, not eyeballed. That reference is the
// Brick/SP screen at 1024x768; both axes scale to 640x480 by exactly 0.625, so the design maps
// over without distortion (measured, not stretched):
//   body   272x132 -> 170x82      outline 12 -> 7       gap 9 -> 6
//   nub     20x80  ->  12x50      body top y 246 -> 154 (= FBH*246/768)
//   percentage centered, 40px below the body
#define REF_W 170
#define REF_H 82
#define REF_T 7
#define REF_GAP 6
static void render(int pct) {
	memset(fb, 0, (size_t)FBP * FBH * 4);

	const uint32_t WHITE = 0x00FFFFFF, BLACK = 0x00000000;
	const int bw = REF_W, bh = REF_H, t = REF_T, gap = REF_GAP;
	const int bx = (FBW - bw) / 2;
	const int by = FBH * 246 / 768;
	const int r_out = 14, r_in = 8;

	fillRound(bx, by, bw, bh, r_out, WHITE);                        // outline...
	fillRound(bx+t, by+t, bw-2*t, bh-2*t, r_out-t, BLACK);          // ...hollowed out
	fillRound(bx + bw, by + (bh - 50)/2, 12, 50, 5, WHITE);         // terminal nub, right, centered

	int ix = bx + t + gap, iy = by + t + gap;
	int iw = bw - 2*(t+gap), ih = bh - 2*(t+gap);
	// Monochrome by design: fill is WHITE and empty stays BLACK. The old green accent and grey
	// "empty" band were ours, not the reference, and made this the odd screen out on the fork.
	// Unknown level (pct < 0) draws an empty cell rather than inventing a reading.
	if (pct > 0) {
		int fwid = iw * pct / 100;
		if (fwid < 4) fwid = 4;              // keep a sliver visible at 1-2% instead of nothing
		if (fwid > iw) fwid = iw;
		fillRound(ix, iy, fwid, ih, r_in, WHITE);
	}

	char buf[8];
	if (pct < 0) snprintf(buf, sizeof buf, "%%");
	else snprintf(buf, sizeof buf, "%d%%", pct);
	drawText(buf, (FBW - textWidth(buf)) / 2, by + bh + 40, WHITE);
}

int main(int argc, char** argv) {
	// TEST HOOK — `batmon.elf --preview N` draws one frame at N% and exits, leaving it on screen.
	// It exists because the acceptance capture and the low/middle/full battery matrix cannot be
	// produced any other way: you cannot make a real cell read 3% and 100% on demand, and the
	// normal path refuses to draw at all unless external power is present. Never used at boot.
	// A typo must not silently drop into the normal blocking charge loop, so --preview with a
	// bad/absent argument is an explicit error rather than a fallthrough.
	int preview = -1;
	if (argc >= 2 && strcmp(argv[1], "--preview") == 0) {
		if (argc < 3) { fprintf(stderr,"usage: batmon.elf --preview <0-100>\n"); return 2; }
		char* end = NULL;
		long pv = strtol(argv[2], &end, 10);
		if (!end || *end || pv < 0 || pv > 100) {
			fprintf(stderr,"batmon: --preview needs 0-100, got \"%s\"\n", argv[2]); return 2;
		}
		preview = (int)pv;
	}

	// POWER PREFLIGHT — one immediate read, before touching the framebuffer or input.
	// batmon now runs on EVERY Plus boot, so the not-charging case must cost ~nothing. The
	// tolerant path below (1s polls, 5 missed reads) exists for a session that is ALREADY
	// established; applying it here put a deterministic ~4s stall in front of every ordinary
	// boot whenever the PMIC read failed. Not charging, or unreadable, means fail open: get out
	// of the way and let the boot continue.
	if (preview < 0) {
		int p0 = isPowered();
		if (p0 <= 0) {
			if (p0 < 0) fprintf(stderr,"batmon: PMIC unreadable at preflight — failing open\n");
			return 0;
		}
	}

	fb_fd = open("/dev/fb0", O_RDWR);
	if (fb_fd < 0) return 0;                // no framebuffer: just let the boot continue
	struct fb_var_screeninfo v; struct fb_fix_screeninfo f;
	// Every stage is checked. This runs before the menu exists, so a failure here has no UI to
	// report through — the only safe outcome is to bail quietly and let the boot continue, never
	// to dereference NULL/MAP_FAILED and take the boot down with it.
	if (ioctl(fb_fd, FBIOGET_VSCREENINFO, &v) < 0 || ioctl(fb_fd, FBIOGET_FSCREENINFO, &f) < 0) {
		fprintf(stderr,"batmon: fb ioctl failed\n"); close(fb_fd); return 0;
	}
	// We write 32bpp words and memset a WHOLE page, so every one of these must hold or the very
	// first draw runs off the mapping (SIGBUS during boot, or silent corruption of whatever else
	// lives there). smem_len != 0 was NOT sufficient: a device reporting less than one page still
	// passed and then got a full-page memset.
	size_t page = (size_t)f.line_length * (size_t)v.yres;
	if (v.xres == 0 || v.yres == 0 || v.bits_per_pixel != 32 ||
	    f.line_length < (size_t)v.xres * 4 ||
	    f.line_length % 4 != 0 ||
	    page / f.line_length != v.yres ||          // multiplication overflow
	    f.smem_len < page) {                       // must cover at least the page we draw
		fprintf(stderr,"batmon: unusable fb geometry %ux%u bpp=%u pitch=%u smem=%u (need >= %zu)\n",
			v.xres, v.yres, v.bits_per_pixel, f.line_length, (unsigned)f.smem_len, page);
		close(fb_fd); return 0;
	}
	FBW = v.xres; FBH = v.yres; FBP = f.line_length / 4;

	// Draw into the page that is actually being scanned out. A previous owner may have left the
	// panel panned to page 1 or 2 — the original wrote page 0 unconditionally, so on those boots
	// its image was invisible and the screen just looked dead.
	size_t off  = (size_t)v.yoffset * (size_t)f.line_length;
	size_t maplen = page * 3 > f.smem_len ? f.smem_len : page * 3;
	int pan_to_zero = 0;
	if (off + page > maplen) {
		// The scanout page is outside what we can map. Falling back to page 0 is only correct if
		// we ALSO pan scanout there — otherwise we draw perfectly into a page nobody is showing,
		// which looks identical to a dead screen (the exact bug this page logic was added for).
		fprintf(stderr,"batmon: yoffset %u outside mapping (%zu) — panning to page 0\n",
			v.yoffset, maplen);
		off = 0;
		pan_to_zero = 1;
	}
	void* fb_base = mmap(NULL, maplen, PROT_READ|PROT_WRITE, MAP_SHARED, fb_fd, 0);
	if (fb_base == MAP_FAILED) { fprintf(stderr,"batmon: mmap failed\n"); close(fb_fd); return 0; }
	// Keep the BASE pointer: fb is offset into the mapping, and munmap must be given the base.
	fb = (uint32_t*)((char*)fb_base + off);
	if (pan_to_zero) {
		v.yoffset = 0;
		if (ioctl(fb_fd, FBIOPAN_DISPLAY, &v) < 0)
			fprintf(stderr,"batmon: pan to page 0 failed — screen may stay blank\n");
	}

	fprintf(stderr,"batmon: fb %dx%d pitch=%d yoffset=%d smem=%u\n",
		FBW, FBH, FBP, v.yoffset, (unsigned)f.smem_len);
	if (preview >= 0) {                       // draw one frame and leave it up for the capture
		render(preview > 100 ? 100 : preview);
		munmap(fb_base, maplen);
		close(fb_fd);
		return 0;
	}

	// FAIL OPEN if we cannot read the power key. Without it POWER cannot leave charge mode, so
	// the only way out is unplugging the cable — a device that appears to have hung. Charge mode
	// is optional; a reachable menu is not.
	int input_fd = open("/dev/input/event0", O_RDONLY | O_NONBLOCK);
	if (input_fd < 0) {
		fprintf(stderr,"batmon: no input device — failing open so POWER still boots\n");
		memset(fb, 0, (size_t)FBP * FBH * 4);
		munmap(fb_base, maplen);
		close(fb_fd);
		return 0;
	}
	struct pollfd pfd = { .fd = input_fd, .events = POLLIN };

	int duty0 = getDuty();
	if (duty0 <= 0) duty0 = 50;
	int dimmed = 0, idle = 0, last = -2;

	int miss = 0;
	while (1) {
		int chg = isPowered();
		if (chg < 0) {                      // transient i2c failure — do NOT treat as unplugged
			fprintf(stderr,"batmon: i2c read failed (%d)\n", miss+1);
			if (++miss >= 5) { fprintf(stderr,"batmon: exit - PMIC unreadable\n"); break; }
		}
		else {
			miss = 0;
			if (!chg) { fprintf(stderr,"batmon: exit - unplugged\n"); break; }
		}

		int pct = battPercent();
		if (pct != last) { render(pct); last = pct; }

		// Blocking poll — no busy-wait. 1s cadence keeps the readout live and costs nothing.
		pfd.revents = 0;
		int r = poll(&pfd, 1, 1000);
		if (r < 0) {
			if (errno == EINTR) continue;   // a signal is not a failure
			fprintf(stderr,"batmon: poll failed (%s) — failing open\n", strerror(errno));
			goto done;
		}
		// A dead fd makes poll return IMMEDIATELY and forever. Without this the loop stops being a
		// 1s cadence, spins a core and hammers the i2c bus for the whole charging session — on a
		// fork whose entire point is not doing that.
		if (r > 0 && (pfd.revents & (POLLHUP|POLLERR|POLLNVAL))) {
			fprintf(stderr,"batmon: input device went away (revents=0x%x) — failing open\n", pfd.revents);
			goto done;
		}
		if (r > 0 && (pfd.revents & POLLIN)) {
			struct bm_event ev;
			ssize_t n;
			while ((n = read(input_fd, &ev, sizeof ev)) == sizeof ev) {
				if (ev.type != BM_EV_KEY) continue;
				if (ev.code == KEY_POWER_ && ev.value == 0) {
					fprintf(stderr,"batmon: exit - POWER\n"); goto done; }
				if (ev.value == 1) { idle = 0; if (dimmed) { setDuty(duty0); dimmed = 0; } }
			}
			if (n < 0 && errno != EAGAIN && errno != EWOULDBLOCK && errno != EINTR) {
				fprintf(stderr,"batmon: input read failed (%s) — failing open\n", strerror(errno));
				goto done;
			}
		}
		else if (r == 0 && ++idle >= 20 && !dimmed) { // ~20s idle: dim, stay responsive, keep drawing
			// Dim, do NOT go dark. setDuty(1) against a period of 800 is indistinguishable from a
			// powered-off panel, and this screen is the ONLY thing on screen while charging — a
			// black rectangle that ignores everything but POWER is exactly the "looks like a hang"
			// report the batmon rewrite existed to end. 6 is the dimmest level the brightness scale
			// itself uses (SetBrightness(0) -> duty 6), so it is known to be visible.
			int dim = duty0 / 4;
			if (dim < 6) dim = 6;
			if (dim > duty0) dim = duty0;
			setDuty(dim);
			dimmed = 1;
		}
	}
done:
	if (dimmed) setDuty(duty0);
	memset(fb, 0, (size_t)FBP * FBH * 4);   // hand a clean screen to the menu
	if (input_fd >= 0) close(input_fd);
	munmap(fb_base, maplen);                // the BASE pointer, not the page-offset one
	close(fb_fd);
	return 0;
}
