#!/usr/bin/env python3
"""Rasterise the digits 0-9 and '%' from the real MinUI font into a C bitmap for batmon.

WHY: the charging screen must match docs/img/charging-screen.png, which is drawn with
BPreplayBold — a rounded geometric bold face. batmon renders straight to /dev/fb0 with no SDL,
no SDL_ttf and no image library (that is deliberate: it runs before the menu exists and must not
drag a toolkit into the boot path). A hand-rolled 5x7 grid cannot imitate that typeface; thickening
it just produced a chunkier wrong font.

So the glyphs are rasterised OFFLINE from the actual font file and embedded as a 1-bit bitmap.
Exact typeface, zero runtime dependencies.

Regenerate with:  python3 tools/gen-batmon-font.py
"""
from PIL import Image, ImageDraw, ImageFont
import pathlib

FONT = pathlib.Path(__file__).parent.parent / "skeleton/SYSTEM/res/BPreplayBold-unhinted.otf"
OUT = pathlib.Path(__file__).parent.parent / "workspace/miyoomini/batmon/font.h"
CHARS = "0123456789%"

# The reference percentage is 38px tall on a 1024x768 screen. batmon renders at 640x480, and both
# axes scale by exactly 0.625, so the target cap height is 38 * 0.625 = 24px.
TARGET_H = 24

# find the pixel size whose digit cap-height lands on TARGET_H
size = TARGET_H
for _ in range(40):
    f = ImageFont.truetype(str(FONT), size)
    box = f.getbbox("0")
    h = box[3] - box[1]
    if h == TARGET_H:
        break
    size += 1 if h < TARGET_H else -1
font = ImageFont.truetype(str(FONT), size)
print(f"font size {size}px -> digit height {font.getbbox('0')[3]-font.getbbox('0')[1]}px")

# Rasterise every glyph on a common baseline so they line up when drawn side by side.
asc = max(font.getbbox(c)[1] for c in CHARS)
desc = max(font.getbbox(c)[3] for c in CHARS)
GH = desc - asc
GW = max(int(font.getlength(c)) for c in CHARS) + 2

glyphs = []
for c in CHARS:
    im = Image.new("L", (GW, GH), 0)
    ImageDraw.Draw(im).text((0, -asc), c, fill=255, font=font)
    rows = []
    for y in range(GH):
        bits = 0
        for x in range(GW):
            if im.getpixel((x, y)) > 110:
                bits |= 1 << x
        rows.append(bits)
    glyphs.append((c, rows, int(font.getlength(c))))

with open(OUT, "w") as fh:
    fh.write("// GENERATED by tools/gen-batmon-font.py -- do not edit by hand.\n")
    fh.write("// Digits 0-9 and '%%' rasterised from BPreplayBold-unhinted.otf, the same face the\n")
    fh.write("// launcher uses, so the charging screen matches docs/img/charging-screen.png exactly.\n")
    fh.write("// One bit per pixel, LSB = leftmost column.\n")
    fh.write(f"#define BM_GW {GW}\n#define BM_GH {GH}\n#define BM_NGLYPH {len(CHARS)}\n")
    fh.write("static const unsigned int BM_FONT[BM_NGLYPH][BM_GH] = {\n")
    for c, rows, _ in glyphs:
        fh.write("\t{" + ",".join(f"0x{r:08X}" for r in rows) + f"}}, // {c}\n")
    fh.write("};\n")
    fh.write("static const unsigned char BM_ADV[BM_NGLYPH] = {"
             + ",".join(str(a) for _, _, a in glyphs) + "};\n")
print(f"wrote {OUT}  ({GW}x{GH} cell, {len(CHARS)} glyphs)")
